version: "3.9"
services:
    web:
        build: .
        ports:
            - "5050:5050"
            - "8000:80"
        environment:
            ASPNETCORE_URLS: "http://+"
            ASPNETCORE_ENVIRONMENT: Development
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"

